apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  labels:
    app: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: ghcr.io/brainstarr/tasky:latest
        ports:
        - containerPort: 8080  # Replace if your app uses another port
        env:
        - name: ENV
          value: production
        - name: MONGODB_URI
          value: mongodb://10.0.1.50:27017
